### ISSUE TITLE
@RxLogSubscriber NullPointerException

### ISSUE THREAD

**Issue by spirosoik** [android10/frodo#14]
There are a few problems with a library dude which I will try to solve and send a PR. I found that if send an empty observable back or a null value back then the RxLogSubscriber crashes with NullPointerException. If I removed it then the subscriber works normally.

**Comment by android10** [comment]
@spirosoik great. If you have more details, please put them here so we can find out what the problem is and solve it :)

**Comment by ANPez** [comment]
I have this very same problem. Logging an observable with fixed elements reproduces the problem on the emulator with Android 4.4. On my Nexus 5 with Android 6 works perfectly. Of course, it only happens when compiled for debug. Below the code that reproduces the problem.

`@Singleton
public class LocalFrames {
  private static final String TAG = LocalFrames.class.getSimpleName();

  private List<Frame> frames = new ArrayList<>();

  @Inject
  public LocalFrames(AssetManager assetManager) {
    // Insert into "frames" a fixed set of elements, read from assets.
  }

  @RxLogObservable
  public Observable<Frame> all() {
    return Observable.from(frames);
  }
}`

**Comment by android10** [comment]
@ANPez thanks for reporting this. I have plans to release a new version by the end of next week with some fixes (this one included).

**Comment by spirosoik** [comment]
Guys I found the problem. Let's assume that for some reason we want to sent back a null observable ```Observable.just(null)```. @android10 [Here](https://github.com/android10/frodo/blob/master/frodo-runtime/src/main/java/com/fernandocejas/frodo/joinpoint/FrodoJoinPoint.java#L50)  you are trying to fetch the args of the Subscriber join point where in this case the ```this.methodParamValuesList``` will be null. 
But the problem is [here](https://github.com/android10/frodo/blob/master/frodo-runtime/src/main/java/com/fernandocejas/frodo/aspect/LogSubscriber.java#L82)  in the ```LogSubscriber#beforeOnNextExecution``` in line 82 method where you are fetching the ```methodParamValuesList``` back where in this case are null so in this line ```value.toString()``` will throw a ```NullPointerException```.

**Comment by spirosoik** [comment]
@android10 @ANPez which you prefer guys?

**Comment by android10** [comment]
@spirosoik good catch! I think since this is an utility library for logging and debugging, it is nice to be defensive. I would vote for both in this case. 
If you have plans to open a PR, we can comment and discuss over there, which in my opinion is the best way since we are directly dealing with the code :). What do you think?

**Comment by spirosoik** [comment]
@android10 I agree i prefer both of them. Yes I will send a PR dude and we can discuss there.

**Comment by android10** [comment]
@spirosoik I really appreciate that man! :+1:

**Comment by spirosoik** [comment]
@android10 Glad to help dude.
